### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by ifredom** [roscoe054/ykit-starter-vue#1]
--> npm install -g ykit

 --> git clone https://github.com/roscoe054/ykit-starter-vue.git

-->  cd ykit-starter-vue

--> npm install

--> npm run dev

访问 http://127.0.0.1:8080 
或者http://127.0.0.1:8080/ykit-starter-vue/index.html  
都是Failure: 404 Not Found

**Comment by yuhaoju** [comment]
我本地试过没有复现，ykit 版本是 0.4.1

方便截个 chrome network 里面 js 404 的状态么，以及控制台的 log

**Comment by papuaer** [comment]
直接运行npm start确实是跑不起来 （window下）  运行ykit server -p 3000才可以运行起来。
即使运行起来 例子里也一堆报错 见下图
![image](https://user-images.githubusercontent.com/22409655/33412343-9f09fb86-d5c5-11e7-83ff-91296ad0c8bb.png)

**Comment by yuhaoju** [comment]
@papuaer 之前不支持 ykit@2，现在已经修复

**Comment by zhangjingsu** [comment]
直接运行npm start会报错，是需要配置其他东西吗？
![image](https://user-images.githubusercontent.com/4568126/60952724-5ddb7f80-a32e-11e9-89e6-bd8d2525eb4a.png)
